clear
clc

% Initialize parameters and load necessary data
% Only Run once every new session
current_dir = fileparts(mfilename('fullpath'));
cd(current_dir);
load nch_18_mac_nominal_1um.mat;

nch_18_mac_nominal = nch_18_mac_nominal_1um;

% User inputs

id = 62e-06;
gm = 12 * id;
gm = 3.14e-04;
id = gm/12;
gm_id = gm/id;
constraint_type = 'GM_GDS';

constraint_value = 27;

switch constraint_type

    case 'GM_GDS'

        L = find_length( ...
            nch_18_mac_nominal, ...
            'GM_GDS', ...
            gm_id, ...
            constraint_value);

    case 'FT'

        L = find_length( ...
            nch_18_mac_nominal, ...
            'FT', ...
            gm_id, ...
            constraint_value);

    otherwise

        error('Unknown constraint type')

end

% Evaluate remaining quantities

gm_gds = lookup( ...
            nch_18_mac_nominal, ...
            'GM_GDS', ...
            gm_id, ...
            L);

ft = lookup( ...
            nch_18_mac_nominal, ...
            'FT', ...
            gm_id, ...
            L);

vov = lookup( ...
            nch_18_mac_nominal, ...
            'VOV', ...
            gm_id, ...
            L);

id_w = lookup( ...
            nch_18_mac_nominal, ...
            'ID_W', ...
            gm_id, ...
            L);

vdsat = lookup( ...
            nch_18_mac_nominal, ...
            'VDSAT', ...
            gm_id, ...
            L);

vth = lookup( ...
            nch_18_mac_nominal, ...
            'VTH', ...
            gm_id, ...
            L);

vgs = vov + vth;

W = id / id_w;

fprintf('\n');
fprintf('Results\n');
fprintf('-------------------------\n');
fprintf('gm/id   = %.2f\n', gm_id);
fprintf('L       = %.3f nm\n', L*1e9);
fprintf('W       = %.3f nm\n', W*1e9);
fprintf('gm/gds  = %.2f\n', gm_gds);
fprintf('ft      = %.3e Hz\n', ft);
fprintf('Vov     = %.3f V\n', vov);
fprintf('Vdsat     = %.3f V\n', vdsat);
% fprintf('Vgs     = %.3f V\n', vgs);
fprintf('\n');